services:
  db:
    image: mysql
    restart: always
    container_name: bp_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beautify_project
      MYSQL_USER: bp
      MYSQL_PASSWORD: bp
      TZ: Asia/Seoul
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/arm64/v8
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
