server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: local
    import:
      - jasypt.yml
      - datasource-local.yml
      - storage-local.yml
      - kafka-local.yml

thread-pool:
  async:
    core-pool-size: 16
    max-pool-size: 32
    queue-capacity: 100
    thread-name-prefix: IO-Async-Executor

logging:
  level:
    org.hibernate.SQL: info
    com.beautify_project.bp_app_api: debug
    org.apache.kafka: debug
    com.p6spy.engine: trace
