server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: test
    import:
      - jasypt.yml
      - datasource-local.yml
      - storage-local.yml
      - mail.yml
      - auth.yml
