server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: local
    import:
      - jasypt.yml
      - auth.yml
      - classpath:mysql-config/application-local.yml
      - classpath:s3-client-config/application-local.yml
      - classpath:kafka-config/kafka-local.yml

thread-pool:
  async:
    core-pool-size: 16
    max-pool-size: 32
    queue-capacity: 100
    thread-name-prefix: IO-Async-Executor

logging:
  level:
    com.bp.app.api: DEBUG
    org.apache.kafka: INFO
