server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: test
    import:
      - jasypt.yml
      - mail.yml
      - classpath:mysql-config/application-local.yml
      - classpath:s3-client-config/application-local.yml
      - classpath:security-config/application..yml

logging:
  level:
    org.hibernate.SQL: debug
    com.beautify_project.bp_app_api: debug
    org.springframework.security: debug
