server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: local
    import:
      - jasypt.yml
      - datasource-local.yml
      - storage-local.yml
      - auth.yml

logging:
  level:
    org.hibernate.SQL: debug
    com.beautify_project.bp_app_api: debug
