server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: prod
    import:
      - jasypt.yml
      - datasource-local.yml
      - storage-local.yml

logging:
  level:
    org.hibernate.SQL: debug
