## BP 서비스 내 발급할 jwt secret key
jwt:
  secret-key: ENC(LDCoYKbeO3g4Qc7Q5BOCDozxdq3jhGzref9JkJnWTi+8rmjNdPoesBFkErpO3Qdd)
  access-token-expired-minute: 60
  refresh-token-expired-minute: 180

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(vgidToDUhCV4eURP7BMoDtqWOz0qPn5UdsbP1JAOj2oZmo8WyKXat0Y+wvByfR8Z)
            client-secret: ENC(LpBUPVDQgo/VQsJUXbtru9Hvua6zP8XskizZY1cQlryfMY3ILvM265cAals+eJcZ)
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, account_email, age_range, birthday
          naver:
            client-id: ENC(Xn8uJnVHQfOmP0vbt8JGX96dlnld20dILMnTdJ6BUX0=)
            client-secret: ENC(1WaE/Y++z90RfneqXAz/qiPFYtH7jiQ2)
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email, nickname, gender, age
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

oauth2-login:
  authorization-endpoint: /v1/auth/oauth2
  redirected-endpoint: /oauth2/callback/*
  success-redirection-url: http://localhost:8080/v1/auth/test/{token} #client url 로 지정되어야 함
