## BP 서비스 내 발급할 jwt secret key
---
jwt:
  secret-key: ENC(kA951a0P++xefWrbSQ1YIZn5aep0rBnJXcmRqLSyvhPf/xyHF241qQ==)
  expired-minute: 60
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(3fc1928e41c31bfa3e85a8e7585f6d0a)
            client-secret: ENC(iGXGQsjIXeF3o98TxxbFIBs4s1i1rEs1)
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, account_email, age_range, birthday
          naver:
            client-id: ENC(Xn8uJnVHQfOmP0vbt8JGX96dlnld20dILMnTdJ6BUX0=)
            client-secret: ENC(1WaE/Y++z90RfneqXAz/qiPFYtH7jiQ2)
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email, nickname, gender, age
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
oauth2-login:
  authorization-endpoint: /v1/auth/oauth2
  redirection-endpoint: /oauth2/callback/*
  success-redirection-url: http://localhost:3000/auth/oauth-response/{token}/
