spring:
  datasource:
    url: ENC(WYQa+sbvAKaZjBGjG3eJYe0zs57sLmydUoHWy3+5K2uIzOX7L0s5Z+eqNqOUB10OkbVNmB7mANhO1LaL4Q1599kNNmzAiII0j93edJCVWErUtIc7hgEV+2L3CexhYg/FRcUBL1vMC4ejtLmgZ+P3NePq/v9EWTE7)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(NewqJfs9tcn1CanlMbtBcw==)
    password: ENC(NewqJfs9tcn1CanlMbtBcw==)

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        batch_size: 100
        order_inserts: true
        order_updates: true
